backend:
    name: git-gateway
    repo: jonathan-grumke/travel-blog
    branch: preview

media_folder: "src/assets/uploads"

logo_url: "https://suninmypocket.com/Logo.svg"

collections:
    - name: "travel-diary"
      label: "Reisetagebuch"
      folder: "src/content/travel-diary"
      create: true
      delete: true
      format: frontmatter
      extension: "mdx"
      fields:
          - { name: "title", label: "Titel", widget: "string" }
          - { name: "description", label: "SEO Description", widget: "text" }
          - { name: "slug", label: "URL", widget: "string" }
          - {
                name: "pubDate",
                label: "Datum",
                widget: "datetime",
                format: "DD MMM YYYY",
                date_format: "DD MMM YYYY",
                time_format: false,
            }
          - { name: "heroImage", label: "Titelbild", widget: "image" }
          - { name: "author", label: "Autor", widget: "string" }
          - { name: "body", label: "Inhalt", widget: "markdown" }
